### PR TITLE
FEG-234 - Feature - admin panels

### PR DESCRIPTION
**Pull request by arthurrigley**
## Summary of Changes
1. Update the third panel example to be simpler and without obvious difference between panel heading and body
2. Update documentation to reflect
3. Confirm dark mode version

## Review
Open up the preview site (see the below netlify comment below) and navigate to:
- /components/panel

## Ticket(s)
FEG-234

## Checklist

The below needs to be done before a pull request can be approved:

- [ ] The pull request command has been ran `npm run pull-request`
- [ ] New components work as a Vue component, Web component and as static HTML
- [ ] New components added as an export to src/index.js
- [ ] New components/features have sufficient unit tests
- [ ] New components/features have sufficient documentation
- [ ] New component has dataLayer events added
- [ ] New component is added to the rollup config

## Accesibility check list

- [ ] New components/features are accessible to keyboard users (All links/buttons are tabbable, All content is accessible)
- [ ] New components/features are accessible to non-JS users (All links/buttons are tabbable, All content is accessible), this may have visual differences
- [ ] New components/features have hover, focus and active states on all the links/buttons
- [ ] New components/features work when in dark mode and high contrast mode. Buttons, links and icons should still look like what they are.

### CODE REVIEW

**Comment by arthurrigley** [comment]
@JamesLambert1986  conflict with `audit.json` - Not sure if you were running the `npm run pull-request` command still, but I ran it and showing a conflict - this is an older branch (69 commits behind), I guess I can just resolve like normal with merging develop into it?

**Comment by JamesLambert1986** [comment]
> @JamesLambert1986 conflict with `audit.json` - Not sure if you were running the `npm run pull-request` command still, but I ran it and showing a conflict - this is an older branch (69 commits behind), I guess I can just resolve like normal with merging develop into it?

Yeah its always best to merge dev into your branch before creating a PR.

**Comment by arthurrigley** [comment]
@JamesLambert1986  merged develop into branch, ran `npm run pull-request` again to resolve the audit, but see some errors - I'll rerun checks...

**Comment by JamesLambert1986** [comment]
@arthurrigley fixed the deploy, it was my fault I did the same on Nat's PR too.

**Review by JamesLambert1986 — APPROVED** [review]

**Pull request merged**
